### ISSUE TITLE
Use reactive() to store object value

### ISSUE THREAD

**Issue by HilmiZul** [Afkar-Saga/idle-dice#1]
Better using `reactive()` instead `ref()` to store object.
https://github.com/Afkar-Saga/idle-dice/blob/7000d1937b9c5bb7f1c1f041e4cc9911400bd81c/src/views/DiceView.vue#L8

More about [Reactivity API](https://vuejs.org/api/reactivity-core.html)

**Comment by Afkar-Saga** [comment]
🍍
